# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [133]:
%tensorflow_version 2.x

UsageError: Line magic function `%tensorflow_version` not found.


### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [ ]:
import tensorflow as tf
print(tf.__version__)

### Set random seed

In [134]:
tf.random.set_seed(42)

In [135]:
import pandas as pd
import seaborn as sns

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [136]:
from sklearn.model_selection import train_test_split
#Irisds = pd.read_csv(".//prices and iris//iris.csv")
#Irisds.head()

In [137]:
#Importing from sklearn library.
from sklearn import datasets
Iris=datasets.load_iris()

In [138]:
type(Iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [139]:
X = Iris.data
y = Iris.target

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [140]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size = 0.25)

In [141]:
ytrain

array([2, 0, 1, 0, 0, 1, 0, 2, 2, 1, 2, 0, 2, 1, 0, 2, 0, 1, 0, 2, 1, 0,
       2, 0, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 0, 2, 0, 1, 2, 2, 0, 1, 2, 2,
       0, 1, 0, 1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 1, 1, 1, 2, 0, 2, 2, 1, 2,
       1, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 2, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0,
       0, 0, 2, 2, 0, 1, 1, 1, 2, 1, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 0, 2,
       0, 0])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [142]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [143]:
nb_classes = 3
ytrain_copy = ytrain.copy()
ytest_copy = ytest.copy()
target1 = np.array([[ytrain]]).reshape(-1)
target2 = np.array([[ytest]]).reshape(-1)
ytrain = np.eye(3)[target1]
ytest = np.eye(3)[target2]

## Question 5

### Initialize a sequential model
- Define a sequential model

In [144]:
import tensorflow as tf


In [145]:
model = tf.keras.models.Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [146]:
inputshape = Xtrain.shape[1:]
model = tf.keras.models.Sequential([
 # tf.keras.layers.Flatten(input_shape=inputshape),
  tf.keras.layers.Dense(4, input_shape=inputshape, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(60, activation='relu'),
  tf.keras.layers.Dense(30, activation='relu'),
  tf.keras.layers.Dense(3, activation='softmax')
])



## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [147]:
model.compile(optimizer='SGD',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [148]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 4)                 20        
_________________________________________________________________
dropout_1 (Dropout)          (None, 4)                 0         
_________________________________________________________________
dense_5 (Dense)              (None, 60)                300       
_________________________________________________________________
dense_6 (Dense)              (None, 30)                1830      
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 93        
Total params: 2,243
Trainable params: 2,243
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [149]:
model.fit(Xtrain, ytrain, epochs=100)
model.evaluate(Xtest,  ytest, verbose=2)

Train on 112 samples
Epoch 1/100
112/112 [==============================] - 0s 2ms/sample - loss: 1.0807 - accuracy: 0.3125
Epoch 2/100
112/112 [==============================] - 0s 49us/sample - loss: 1.0651 - accuracy: 0.3839
Epoch 3/100
112/112 [==============================] - 0s 53us/sample - loss: 1.0697 - accuracy: 0.3571
Epoch 4/100
112/112 [==============================] - 0s 71us/sample - loss: 1.0752 - accuracy: 0.3393
Epoch 5/100
112/112 [==============================] - 0s 62us/sample - loss: 1.0763 - accuracy: 0.3214
Epoch 6/100
112/112 [==============================] - 0s 62us/sample - loss: 1.0749 - accuracy: 0.3214
Epoch 7/100
112/112 [==============================] - 0s 71us/sample - loss: 1.0649 - accuracy: 0.3661
Epoch 8/100
112/112 [==============================] - 0s 45us/sample - loss: 1.0632 - accuracy: 0.3482
Epoch 9/100
112/112 [==============================] - 0s 71us/sample - loss: 1.0675 - accuracy: 0.3214
Epoch 10/100
112/112 [======================

112/112 [==============================] - 0s 53us/sample - loss: 0.6168 - accuracy: 0.6607
Epoch 79/100
112/112 [==============================] - 0s 62us/sample - loss: 0.6483 - accuracy: 0.5536
Epoch 80/100
112/112 [==============================] - 0s 53us/sample - loss: 0.6751 - accuracy: 0.6339
Epoch 81/100
112/112 [==============================] - 0s 53us/sample - loss: 0.6617 - accuracy: 0.5536
Epoch 82/100
112/112 [==============================] - 0s 53us/sample - loss: 0.6952 - accuracy: 0.5357
Epoch 83/100
112/112 [==============================] - 0s 62us/sample - loss: 0.6441 - accuracy: 0.5893
Epoch 84/100
112/112 [==============================] - 0s 62us/sample - loss: 0.5891 - accuracy: 0.7232
Epoch 85/100
112/112 [==============================] - 0s 71us/sample - loss: 0.6833 - accuracy: 0.5982
Epoch 86/100
112/112 [==============================] - 0s 62us/sample - loss: 0.6479 - accuracy: 0.5982
Epoch 87/100
112/112 [==============================] - 0s 71us/samp

[0.5159237714190232, 0.81578946]

## Question 10

### Make predictions
- Predict labels on one row

In [150]:
print("Features for 1 row",Xtest[2])
classes = model.predict([[Xtest[2]]])
print("Predicted values ",classes)

Features for 1 row [5.8 4.  1.2 0.2]
Predicted values  [[0.94493634 0.03767908 0.01738469]]


### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [151]:
print("Features for 1 row",Xtest[2])
print("Actual result",ytest[2])

Features for 1 row [5.8 4.  1.2 0.2]
Actual result [1. 0. 0.]




---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

%tensorflow_version 2.x    #Not using this as it is executed in my own laptop with TFv2.0

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [152]:
import tensorflow as tf
print(tf.__version__)

2.0.0


### Set random seed

In [153]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

#Nisha - skipping as running from personal laptop. 
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

In [191]:
prices = pd.read_csv(".//prices and iris//prices.csv")
prices.head()

date symbol        open       close         low        high  \
0  2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998  126.250000   
1  2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002  125.540001   
2  2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000  119.739998   
3  2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000  117.440002   
4  2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996  117.330002   

      volume  
0  2163600.0  
1  2386400.0  
2  2489500.0  
3  2006300.0  
4  1408600.0

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [192]:
prices.drop(['date','symbol'],axis = 1, inplace = True)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [193]:
del prices1000
prices1000 = prices.loc[:999,:]
prices1000.shape

(1000, 5)

In [194]:
prices1000.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [195]:
features = prices1000[['open', 'close', 'low', 'high']]
features.head(2)

open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001

In [196]:
label = prices1000[['volume']]

In [197]:
label.head(2)

volume
0  2163600.0
1  2386400.0

In [198]:
label = label/1000000

In [199]:
label.head(2)

volume
0  2.1636
1  2.3864

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [200]:
type(features),type(label)

(pandas.core.frame.DataFrame, pandas.core.frame.DataFrame)

In [201]:
features = features.to_numpy()
label = label.to_numpy()
type(features),type(label)

(numpy.ndarray, numpy.ndarray)

In [202]:
features.dtype, label.dtype

(dtype('float64'), dtype('float64'))

In [203]:
features = features.astype('float32')
label = label.astype('float32')
features.dtype, label.dtype

(dtype('float32'), dtype('float32'))

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [204]:
features1 = tf.math.l2_normalize(
    features,
    axis=None,
    epsilon=1e-12,
    name=None
)

In [205]:
features1

<tf.Tensor: id=7177, shape=(1000, 4), dtype=float32, numpy=
array([[0.02202894, 0.02245906, 0.02182905, 0.02253223],
       [0.02235197, 0.02141321, 0.02140607, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051192, 0.02137037],
       ...,
       [0.00505436, 0.00513467, 0.00499903, 0.00514181],
       [0.00785282, 0.0079956 , 0.0078082 , 0.00799738],
       [0.00643931, 0.00662849, 0.00642682, 0.00664455]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [206]:
#tf.zeros([1000, 5], tf.float32)
W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]), name="Bias")
print(W)
print(b)

<tf.Variable 'Weights:0' shape=(4, 1) dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>
<tf.Variable 'Bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>


## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [211]:
@tf.function
def prediction(features1,W,b):
    yPred = tf.add(tf.matmul(features1,W),b,name='output')
    return yPred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [212]:
@tf.function
def calloss(label,yPred):
    loss = tf.reduce_mean(tf.square(label-yPred))
    return loss

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [209]:
def train(inputs, outputs,W,b,learning_rate):
    with tf.GradientTape() as t:
        t.watch([W,b])
        curr_pred = prediction(inputs,W,b)
        current_loss = calloss(outputs,curr_pred)
    dW, db = t.gradient(current_loss, [W,b])
    W.assign_sub(learning_rate * dW)  #  W = W - lr*dW
    b.assign_sub(learning_rate * db)
    return (W,b)

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [214]:
for i in range(100):
    W,b = train(features1,label,W,b,0.02)
    print('Current Training loss on iteration',i,calloss(label,prediction(features1,W,b)))

Current Training loss on iteration 0 tf.Tensor(231.15013, shape=(), dtype=float32)
Current Training loss on iteration 1 tf.Tensor(229.41672, shape=(), dtype=float32)
Current Training loss on iteration 2 tf.Tensor(227.8193, shape=(), dtype=float32)
Current Training loss on iteration 3 tf.Tensor(226.34724, shape=(), dtype=float32)
Current Training loss on iteration 4 tf.Tensor(224.9906, shape=(), dtype=float32)
Current Training loss on iteration 5 tf.Tensor(223.74037, shape=(), dtype=float32)
Current Training loss on iteration 6 tf.Tensor(222.5882, shape=(), dtype=float32)
Current Training loss on iteration 7 tf.Tensor(221.52641, shape=(), dtype=float32)
Current Training loss on iteration 8 tf.Tensor(220.54791, shape=(), dtype=float32)
Current Training loss on iteration 9 tf.Tensor(219.64618, shape=(), dtype=float32)
Current Training loss on iteration 10 tf.Tensor(218.8151, shape=(), dtype=float32)
Current Training loss on iteration 11 tf.Tensor(218.04932, shape=(), dtype=float32)
Curren

### Observe values of Weight
- Print the updated values

In [215]:
print(f'Updates Weight (W) values are: \n{W.numpy()}')

Updates Weight (W) values are: 
[[-0.00995435]
 [-0.00950616]
 [-0.00957756]
 [-0.00977882]]


### Observe values of Bias
- Print the updated values

In [216]:
print(f'Updates Bias(b) value is: \n{b.numpy()}')

Updates Bias(b) value is: 
[5.231433]
